module.exports =
  'account-index':      require './account'
  'account-manage':     require './account/manage'
  'auth-forgot':        require './auth/login'
  'auth-login':         require './auth/login'
  'auth-logout':        require './auth/logout'
  'auth-reset':         require './auth/login'
  'auth-choose':        require './auth/choose'
  'auth-signup':        require './auth/signup'
  'home':               require './home'
  'classified-edit':    require './home/edit'
  'classified-post':    require './home/post'
  'classified-search':  require './home/search'
  'classified-single':  require './home/single'
  'landing':            require './landing'
  'privacy':            require './privacy'
  'walkthrough':        require './walkthrough'
  'terms':              require './terms'